name: PR CI
on:
  workflow_dispatch:
  pull_request:
    types:
    # defaults
      - opened
      - synchronize
      - reopened
    # draft handling
      - ready_for_review
      - converted_to_draft

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CYPRESS_INSTALL_BINARY: 0

jobs:
  # https://github.com/orgs/community/discussions/26671
  setup-env:
    name: Setup env
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.save-version.outputs.version }}
    steps:
      - name: Fail on draft PRs if run-ci-on-draft label is not present.
        if: ${{ github.event.pull_request.draft == true && !contains(github.event.pull_request.labels.*.name, 'run-ci-on-draft') }}
        run: |
          echo "::error ::Add the run-ci-on-draft label to your draft PR if the pipeline should run."
          exit 1

      - uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Save Version
        id: save-version
        run: echo "version=$(cat package.json | jq '.version' | xargs)-PR-${{ github.event.number }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

  build-microservices:
    name: Build microservices
    needs: [setup-env]
    uses: ./.github/workflows/build-microservices.yml
    with:
      version: ${{ needs.setup-env.outputs.version }}

  pipeline-success:
    name: Pipeline success
    needs: [setup-env, build-microservices]
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.build-microservices.result == 'success') }}
    steps:
      - name: Success
        run: echo "All required checks passed"
