name: Semantic-Release
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  CYPRESS_INSTALL_BINARY: 0
  GIT_AUTHOR_NAME: 'github-actions[bot]'
  GIT_AUTHOR_EMAIL: 'github-actions[bot]@users.noreply.github.com'
  GIT_COMMITTER_NAME: 'github-actions[bot]'
  GIT_COMMITTER_EMAIL: 'github-actions[bot]@users.noreply.github.com'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Set release tag
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save initial Version
        id: save-initial-version
        run: echo "version=$(cat package.json | jq '.version' | xargs)" >> $GITHUB_OUTPUT

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: ${{ github.server_url }}
          HUSKY: 0
          BRANCH: ${{ github.ref }}
        run: npx semantic-release

      - name: Save new Version
        id: save-new-version
        run: echo "version=$(cat package.json | jq '.version' | xargs)" >> $GITHUB_OUTPUT

      - name: Display result
        run: |
          echo "Initial version: ${{ steps.save-initial-version.outputs.version }}"
          echo "New version: ${{ steps.save-new-version.outputs.version }}"
